### PR TITLE
Update repository pages

### LINKED ISSUE #26: Create link like button style and label control
**Is your feature request related to a problem? Please describe.**

*None*

**Describe the solution you'd like**

Replace the link in the GitHub site with a button to update the style.
Create resource dictionary for this.

**Describe alternatives you've considered**

**Additional context**

**Screenshots (optional)**

Suggested place:

image

### LINKED ISSUE #31: Repository page ScrollViewer position
**Describe the bug**
As the title

**To Reproduce**
1. Go to repository page
2. Scroll down

**Expected behavior**

I don't know where to make it scrollable.

**Screenshots (optional)**

**Version**
 - Windows: Win11 22523.rs_prerelease
 - FluentHub: unversioning

**Additional context**

### PR DESCRIPTION
**Pull request by onein528**
**Resolved / Related Issues**
- Closes #26
- Closes #31 
- Marge commit https://github.com/fluenthub-uwp/FluentHub/commit/c071b1be2f4e92193956017363fa6c3feeb6ff16

**Details of Changes**

*None yet*

**Objective**

- [ ] View all contents in repository
- [x] Add repository's issue page
- [ ] Add repository's PR page
- [x] Add label control (such as issue label, pro plan label, or comments count label)
- [ ] Add status label control(Open or Close or Marge).

**Validation**
How did you test these changes?
- [x] Built and ran the app
- [ ] Tested the changes for accessibility

**Screenshots (optional)**

### CODE REVIEW

**Comment by onein528** [comment]
I want you to marge this commit https://github.com/fluenthub-uwp/FluentHub/commit/c071b1be2f4e92193956017363fa6c3feeb6ff16. but you can right now, can I marge this?

**Comment by BobbyESP** [comment]
> I want you to marge this commit [c071b1b](https://github.com/fluenthub-uwp/FluentHub/commit/c071b1be2f4e92193956017363fa6c3feeb6ff16). but you can right now, can I marge this?

I need to take a look to that commit another time and see how can i do it now. Today (for me) i won't be able to code :( By the moment it's good to keep the flyout that we have.

**Review by BobbyESP — DISMISSED** [review]
All files and changes good!

**Comment by onein528** [comment]
image

**Comment by BobbyESP** [comment]
Nicee!

**Review by fluenthub-observer — DISMISSED** [review]

**Review by BobbyESP — APPROVED** [review]
Theey seem all good!

**Comment by onein528** [comment]
hmm it may be not yet.
We have to reach our objective.

> **Objective**
> - [ ] View all contents in repository
> - [x] Add repository's issue page
> - [ ] Add repository's PR page
> - [x] Add label control (such as issue label, pro plan label, or comments count label)
> - [ ] Add status label control(Open or Close or Marge).

**Comment by fluenthub-observer** [comment]
OK marge this. I'll open another PR.

**Comment by BobbyESP** [comment]
Ok, no problem! May i'll be working this night (yours 6:00 PM)

**Pull request merged**
