### PR TITLE
Create Privacy Policy.md

### PR DESCRIPTION
**Pull request by BobbyESP**
**Resolved / Related Issues**
Items resolved / related issues by this PR.
- Closes #issue...
- Related #issue...

**Details of Changes**
Add details of changes here.
- Added...
- Fixed...

**Validation**
How did you test these changes?
- [ ] Built and ran the app
- [ ] Tested the changes for accessibility

**Screenshots (optional)**
Add screenshots here.

### CODE REVIEW

**Comment by onein528** [comment]
If you dont want to run Build Pipeline, you can create commit message like this:

```
Create Privacy Policy.md
[skip ci]
```

**Comment by onein528** [comment]
LGTM

**Comment by BobbyESP** [comment]
Ok, thanks!

**Review by onein528 — APPROVED** [review]

**Comment by onein528** [comment]
CodeFactor takes us much more time than expected.

**Comment by BobbyESP** [comment]
Yeah... I'm gonna take a look to it.

**Comment by BobbyESP** [comment]
Or maybe making it not required

**Comment by onein528** [comment]
ok

**Pull request merged**
