### PR TITLE
Update file structure

### LINKED ISSUE #65: Issue/PR page scrollviewer position
## 1. (I like)

image

## 2. (Current)

image

## 3. (Hmmm)

image

### PR DESCRIPTION
**Pull request by onein528**
**Resolved / Related Issues**

- Closes #65

**Details of Changes**

- Prepare to publish version 0.7.0

**Validation**
How did you test these changes?
- [x] Built and ran the app
- [ ] Tested the changes for accessibility

**Screenshots (optional)**

### CODE REVIEW

**Comment by onein528** [comment]
I think I need to publish the bundle to the GitHub release before publishing it to the store, and publish it after creating a stable version there.

**Comment by onein528** [comment]
And We discuss FluentHub's versioning.

**Comment by BobbyESP** [comment]
> I think I need to publish the bundle to the GitHub release before publishing it to the store, and publish it after creating a stable version there.

Ok! I think the same

**Comment by BobbyESP** [comment]
> And We discuss FluentHub's versioning.

image
Something like this

**Comment by BobbyESP** [comment]
> > And We discuss FluentHub's versioning.
> 
> image
> 
> Something like this

or this 
image

**Comment by onein528** [comment]
NICE!

**Comment by onein528** [comment]
I want publish testing bundle before becoming v1.0.0

**Comment by onein528** [comment]
I want publish testing bundle before becoming v1.0.0

**Comment by BobbyESP** [comment]
Ok!

**Review by BobbyESP — APPROVED** [review]

**Comment by BobbyESP** [comment]
When you want!

**Comment by onein528** [comment]
ok fix 66  67!

**Comment by BobbyESP** [comment]
Now i'm going to sleep sorry :(

**Pull request merged**
