### PR TITLE
Add repository's latest commit message

### LINKED ISSUE #28: Repos with no description crashing the app
**Describe the bug**
Same as the title

**To Reproduce**
1. Go to a repository that has no description-

**Expected behavior**
Open the repository having no description

**Screenshots (optional)**
Cna't, just this 
image

**Version**
 - Windows:
 - FluentHub:

**Additional context**
No

### PR DESCRIPTION
**Pull request by BobbyESP**
**Resolved / Related Issues**
Items resolved / related issues by this PR.
- Closes #28

**Details of Changes**
Add details of changes here.
- Fixed app crashing when a repository has no description.

**Validation**
How did you test these changes?
- [ ] Built and ran the app
- [ ] Tested the changes for accessibility

**Screenshots (optional)**
Add screenshots here.

### CODE REVIEW

**Comment by onein528** [comment]
????

**Comment by BobbyESP** [comment]
Sorry omg, what i've done. My branches are becoming crazy

**Comment by BobbyESP** [comment]
Sorry a lot :(

**Comment by BobbyESP** [comment]
Close it

**Comment by onein528** [comment]
oh. sorry branch conflict occured.

**Comment by BobbyESP** [comment]
No problem!

**Pull request closed without merging**
