### PR TITLE
Fix azure pipelines

### PR DESCRIPTION
**Pull request by onein528**

### CODE REVIEW

**Comment by onein528** [comment]
Fixed pipeline

**Comment by BobbyESP** [comment]
NICE MENN!!

**Comment by onein528** [comment]
it's very complicated 😭

**Comment by onein528** [comment]
can you review?

**Review by BobbyESP — APPROVED** [review]
Now pipeline works, so nice!

**Comment by onein528** [comment]
Thanks!!

**Comment by BobbyESP** [comment]
All the time Azure gives me 401

**Comment by BobbyESP** [comment]
> it's very complicated sob

I see :(

**Comment by onein528** [comment]
> All the time Azure gives me 401

hmmmmm. I want fix if I can.....

**Comment by onein528** [comment]
whay did you revert?

**Comment by BobbyESP** [comment]
Oh what

**Comment by BobbyESP** [comment]
I think it doesnt affect to the main branch

**Comment by BobbyESP** [comment]
Let me check

**Comment by onein528** [comment]
https://github.com/fluenthub-uwp/FluentHub/commit/add620970b709c20a5fc73b3c2dd4e94d2a46e4c

> I think it doesnt affect to the main branch

Yeah. so, no problem sorry-

**Comment by BobbyESP** [comment]
No, it was my fault, sorry!

**Comment by onein528** [comment]
No problem because this branch will be deleted.

**Pull request merged**
