### PR TITLE
Add zh-CN(Simplified Chinese) Translation

### PR DESCRIPTION
**Pull request by Gaoyifei1011**
Update Simplified Translation in dev

**Resolved / Related Issues**
Items resolved / related issues by this PR.
- Closes #issue...
- Related #issue...

**Details of Changes**
Add details of changes here.

目前在FluentHub Dev提供了一次简单的简体中文翻译，待到您的项目完成之后我再进行其余剩下的翻译
FluentHub Dev currently provides a simple simplified Chinese translation, I will do the rest after your project is completed

- Added...
- Fixed...

**Validation**
How did you test these changes?
- [×] Built and ran the app
- [ ] Tested the changes for accessibility

**Screenshots (optional)**
Add screenshots here.

### CODE REVIEW

**Review by onein528 — APPROVED** [review]

**Comment by onein528** [comment]
LGTM!

**Comment by onein528** [comment]
@BobbyESP Do you have any ideas that run Azure pipelines in fork repos?

**Comment by BobbyESP** [comment]
image
Bruh

**Comment by onein528** [comment]
@Gaoyifei1011 Thank you!

**Pull request merged**
