### PR TITLE
Update the UI of the user profile page

### PR DESCRIPTION
**Pull request by onein528**
**Resolved / Related Issues**

None

**Details of Changes**

As title of this PR

**Validation**
How did you test these changes?

- [x] Built and ran the app
- [ ] Tested the changes for accessibility

**Screenshots (optional)**

image

### CODE REVIEW

**Comment by onein528** [comment]
dont marge yet

**Review by BobbyESP — APPROVED** [review]
All looks good to me. Nice work!

**Comment by onein528** [comment]
Mark as draft.

**Comment by BobbyESP** [comment]
Yeah, leave it as draft

**Comment by onein528** [comment]
I thought ItemsRepeater was the best way to do it like this:
```xml
<muxc:ItemsRepeater>
    <Template>
        <FontIcon/>
        <TextBlock/>
    </Template>
</muxc:ItemsRepeater>
```
but the followers, following, and URL block is a button element.
So it can't be realized with ItemsRepeater.
We need another way.

**Comment by BobbyESP** [comment]
> I thought ItemsRepeater was the best way to do it like this:
> 
> ```
> <muxc:ItemsRepeater>
>     <Template>
>         <FontIcon/>
>         <TextBlock/>
>     </Template>
> </muxc:ItemsRepeater>
> ```
> 
> but the followers, following, and URL block is a button element. So it can't be realized with ItemsRepeater. We need another way.

Ok, no problem. I'll take a look to it later, sorry.

**Comment by onein528** [comment]
There may be a way to make the ItemsRepeater as follows, instantiate the Button or HyperLinkButton in code and add it to the StackPanel's Child.
```xml
<muxc:ItemsRepeater>
    <Template>
        <FontIcon/>
        <StackPanel Child="{x:Bind child}"/>
    </Template>
</muxc:ItemsRepeater>
```

**Comment by BobbyESP** [comment]
Oh yeah, it can be a good idea

**Comment by onein528** [comment]
OK. I'm looking for information about this.

**Comment by BobbyESP** [comment]
Wow sorry.

**Comment by BobbyESP** [comment]
The school keyabords scares me. They do whatever they want

**Comment by onein528** [comment]
FYI
image

**Comment by BobbyESP** [comment]
I wanted to say sorry because i cant talk a lot now :(

**Comment by BobbyESP** [comment]
> FYI image

OH, ok thanks!

**Comment by onein528** [comment]
No, problem!
I'm also a student, so I don't have much time like you.

**Comment by BobbyESP** [comment]
> No, problem! I'm also a student, so I don't have much time like you.

Ok, thanks! And hope you the best in the school. This app can be revolutionary!

**Comment by onein528** [comment]
Thank you for saying that ;)

**Comment by BobbyESP** [comment]
> Thank you for saying that ;)

Thank you to you!

**Comment by onein528** [comment]
image

image

I implemented all these controls in C#. It's extremely redundant. So, instead of WrapLayout of Tookit UI Control, use StackLayout of muxc and make do with the horizontal scroll bar.

**Comment by onein528** [comment]
I will also add a Follow button and a sponsor button in the upper right corner like the repository page:

image

**Comment by BobbyESP** [comment]
> I will also add a Follow button and a sponsor button in the upper right corner like the repository page:
> 
> image
> 

Okk, that's cool!

**Comment by onein528** [comment]
> image
> 
> image
> 
> I implemented all these controls in C#. It's extremely redundant. So, instead of WrapLayout of Tookit UI Control, use StackLayout of muxc and make do with the horizontal scroll bar.
> 
> What do you think about this? If you can fix this, we will go with wrap layout.

Fixed this.

**Comment by onein528** [comment]
I find this. I'll replace with this:
image
This control  can wrap the contents
image

**Comment by BobbyESP** [comment]
Nice!

**Comment by onein528** [comment]
Done.
image

**Comment by onein528** [comment]
Next stage is navigation manager implementation.

**Comment by onein528** [comment]
Finnaly, done :) @BobbyESP  Please approve this.

**Review by BobbyESP — APPROVED** [review]
All look nice!

**Comment by BobbyESP** [comment]
> Finnaly, done :) @BobbyESP Please approve this.

Sorry for the late, approved!

**Comment by BobbyESP** [comment]
Ok i found a bug in this branch

**Comment by BobbyESP** [comment]
But no problem, we can easily fix it

**Comment by BobbyESP** [comment]
Didn't found info in the library docs

**Comment by BobbyESP** [comment]
image

**Comment by BobbyESP** [comment]
image

**Comment by BobbyESP** [comment]
@onein528

**Comment by onein528** [comment]
sorry i will fox this

**Comment by BobbyESP** [comment]
No problem!

**Comment by BobbyESP** [comment]
Do you have Discord or something better to talk?

**Comment by onein528** [comment]
Fixed

**Comment by BobbyESP** [comment]
No problem! I told you that for our comfort, but no problem, better talking here!

**Comment by BobbyESP** [comment]
> Fixed

Ok, good!

**Comment by BobbyESP** [comment]
What it was?

**Comment by onein528** [comment]
> No problem! I told you that for our comfort, but no problem, better talking here!

Did you want to talk on the microphone? You can speak English, but I can't speak English very well.

I have already Discord account. So we can talk.

**Comment by onein528** [comment]
https://discord.gg/NCYWeDW5

**Comment by BobbyESP** [comment]
> > No problem! I told you that for our comfort, but no problem, better talking here!
> 
> Did you want to talk on the microphone? You can speak English, but I can't speak English very well. so I want to talk in text messages.
> 
> I have already Discord account. So we can talk.

No, by writing.

**Pull request merged**
