### PR TITLE
Update app settings pages

### LINKED ISSUE #8: Add multi-account support
### Before you start...

- [X] Have you updated the FluentHub? You might be using an old version.
- [X] Have you checked if similar issue have already been reported?

### What windows are you seeing the problem on?

Windows 11

### What FluentHub version/architecture are you seeing the problem on?

_None_

### Description

As the title

### Steps To Reproduce

_No response_

### Expected behavior

_No response_

### Relevant Assets

_No response_

### PR DESCRIPTION
**Pull request by BobbyESP**
**Resolved / Related Issues**

- Closes #8 (if we can)

**Details of Changes**

- Added the possibility to change the theme of the App (Light/Dark)

**Validation**

- [x] Built and ran the app
- [x] Tested the changes for accessibility

**Screenshots (optional)**

image

**Known bugs**

- The app doesn't save the theme selection after reopening the app

### CODE REVIEW

**Review by onein528 — DISMISSED** [review]
so far, LGTM!

**Comment by BobbyESP** [comment]
Ok, seeing the code i saw that the settings manager has an option to choose the theme. Need to take a look to it, that's why i made this a draft

**Comment by BobbyESP** [comment]
image

**Comment by onein528** [comment]
just coded. so, no dependencies. you can delete it.

**Comment by BobbyESP** [comment]
Ok! But i need to take a look for it by the way.

**Comment by BobbyESP** [comment]
Ok!

**Comment by BobbyESP** [comment]
If you're looking for the bug that doesn't save the theme, i need to say that the theme helper already have the option to save the theme and load it. If you go to the App.xaml file, you can see that there is an `ThemeHelper.Initialize()`. It does that function

**Comment by onein528** [comment]
Thank you. but I will improve only UI!
If I can afford it, I will refer to it.

**Comment by BobbyESP** [comment]
I'm gonna translate the app to the Spanish

**Comment by BobbyESP** [comment]
Nice! I thought on it!

**Review by onein528 — DISMISSED** [review]
Good.

**Comment by onein528** [comment]
Updated UI

image

**Comment by onein528** [comment]
How do you feel?

**Comment by BobbyESP** [comment]
WinUI is a little bit buggy

**Comment by onein528** [comment]
oh. nice! no problem!

**Comment by BobbyESP** [comment]
I had put the pencil icon in the theme selection instead of the brush because I couldn't find it hahah

**Comment by BobbyESP** [comment]
> > The way that i did the theme color saving is not the best, but by the moment, we can keep it
> 
> nice. Whatever it is, both the language and the theme have been preserved and restored.

Yeahh haha nice

**Comment by BobbyESP** [comment]
> (mine 0:14 AM) so I have to sleep. bye. and I'll think about the "About Us" UI tomorrow.

Ok! Good night! I'll try to do it by seeing other apps if you want

**Comment by onein528** [comment]
yea. especially Files' settings and PowerToys, DevToys,,,

**Comment by BobbyESP** [comment]
Yep! Ok, so i'm gonna do a draft and you see if you like it!

**Comment by onein528** [comment]
yeah. it's very complicated.

**Comment by onein528** [comment]
why did you copied FluentIcons to our projects? you considered in windows 10?

**Comment by onein528** [comment]
i changed fontfamily name "Fluent Icons" to "FluentIcons"

**Comment by BobbyESP** [comment]
Ok, nice!

**Comment by BobbyESP** [comment]
> why did you copied FluentIcons to our projects? you considered in windows 10?

? I didn't understand. I putted the font in the assets folder to use the Fluent Icons in the settings views and some others

**Comment by onein528** [comment]
in fact, you can use without specifying.

**Comment by onein528** [comment]
can you see discrod?

**Comment by onein528** [comment]
Add Dev label in app icons

image

**Comment by BobbyESP** [comment]
Nice!

**Comment by onein528** [comment]
you want to stay in private member?
or you can go in public member ([setting](https://github.com/orgs/fluenthub-uwp/people)).

**Comment by onein528** [comment]
image

**Comment by BobbyESP** [comment]
What's the difference?

**Comment by BobbyESP** [comment]
But i can be a public one!

**Comment by BobbyESP** [comment]
Oh, i see. I can be public!

**Comment by onein528** [comment]
Nothing in particular. ;)

**Comment by BobbyESP** [comment]
I thought on doing th website, but first is better to do the main app features

**Comment by onein528** [comment]
yeah. i think the same as you.

**Comment by onein528** [comment]
But I will sleep (1:21 am now)

**Comment by BobbyESP** [comment]
Ok, no problem! Sorry men, and good night!

**Comment by BobbyESP** [comment]
Now i'm going to sleep (0:53 AM Now), tomorrow morning i'll be taking a look to the issues and things that i can do. I f you want, give me a list of things to do and i will be taking a look to them. Thanks!

**Comment by onein528** [comment]
when change language, load custom restart info bar:

image

**Comment by onein528** [comment]
but it does not work.

**Comment by BobbyESP** [comment]
No problem! later i take a look to it

**Comment by BobbyESP** [comment]
Sorry omg, these are mine worst ever weeks

**Comment by onein528** [comment]
you dont have to keep previous code.

**Comment by onein528** [comment]
nice

**Comment by onein528** [comment]
What is the goal of this PR?
Add theme changablity?
You want to merge?

**Comment by BobbyESP** [comment]
For the users, i think that we can do a flyout

**Comment by BobbyESP** [comment]
> What is the goal of this PR? Add theme changablity? You want to merge?

At first, it was for implementing the Dark/Light modes

**Comment by onein528** [comment]
what kind?

**Comment by BobbyESP** [comment]
image
Like this, but for users, i can do a draft

**Comment by onein528** [comment]
oh this is Rise media player.

**Comment by BobbyESP** [comment]
> oh this is Rise media player.

Yep

**Comment by onein528** [comment]
So. What is your ultimate goal?

**Comment by BobbyESP** [comment]
Let me make a Photoshop fast draft

**Comment by onein528** [comment]
this Rise Media Player's expandable content user control is very to windows 11 settings!
Do you want to include this feature?

**Comment by BobbyESP** [comment]
image
Like this! More worked, of course, but this is the idea

**Comment by BobbyESP** [comment]
In app, something like this 
image

**Comment by onein528** [comment]
You want to create settings pages as dialogs?

**Comment by onein528** [comment]
OHHHH. SORRRY

**Comment by BobbyESP** [comment]
> You want to create settings pages as dialogs?

No, just account switching

**Comment by BobbyESP** [comment]
> OHHHH. SORRRY

No problem!

**Comment by onein528** [comment]
you taking about account page?

**Comment by BobbyESP** [comment]
> you taking about account page?

If you want, ok!

**Comment by onein528** [comment]
uhm, I'm sorry, I don't understand at all.

**Comment by onein528** [comment]
you want to change accoutn selector to dropdown?

**Comment by BobbyESP** [comment]
Ok, i tell you, sorry. I want to change 
image

**Comment by onein528** [comment]
okok.

**Comment by BobbyESP** [comment]
And convert that to a ContentDialog

**Comment by BobbyESP** [comment]
image
Like this

**Comment by onein528** [comment]
ok, why?

**Comment by BobbyESP** [comment]
Oh, it's ok, so we can keep it! It was an idea haha

**Comment by onein528** [comment]
I'm sorry for my lack of understanding

**Comment by BobbyESP** [comment]
No problem! I explained that bad as f*ck

**Comment by onein528** [comment]
so, merge this? or still stay?

**Comment by BobbyESP** [comment]
We can merge it

**Comment by onein528** [comment]
Ill fix codefactor

**Comment by BobbyESP** [comment]
Ok!

**Review by onein528 — APPROVED** [review]

**Pull request merged**
