### PR TITLE
Update repository code page

### LINKED ISSUE #10: Use DiffPlex.UWP for displaying commit diff
### Before you start...

- [X] Have you updated the FluentHub? You might be using an old version.
- [X] Have you checked if similar issue have already been reported?

### What windows are you seeing the problem on?

Windows 11

### What FluentHub version/architecture are you seeing the problem on?

_None_

### Description

We can get the text comparer from [this](https://github.com/veler/DevToys) repo.

### Steps To Reproduce

_No response_

### Expected behavior

_No response_

### Relevant Assets

image

### LINKED ISSUE #27: Fix relative path in the html string
**Describe the bug**

This issue exists to link to PR.

**To Reproduce**

**Expected behavior**

**Screenshots (optional)**

**Version**
 - Windows:
 - FluentHub:

**Additional context**

### LINKED ISSUE #43: When clicking a pinned repo block before it's completely loaded, the app crashes
**Describe the bug**

**To Reproduce**
1. Go to your profile and click some pinned repo before it's loaded (name, description...)
2. Click on it
3. See the app crashing

**Expected behavior**
Open the repo page anyways.

**Screenshots (optional)**
https://user-images.githubusercontent.com/60316747/152652468-60dc54ae-c660-4ce9-9989-8b5c28c64733.mp4

and

image

**Version**
 - Windows: 11
 - FluentHub: Not yet versioned

**Additional context**
No

### LINKED ISSUE #45: When there is no internet connection, the app crashes
### Before you start...

- [X] Have you updated the FluentHub? You might be using an old version.
- [X] Have you checked if similar issue have already been reported?

### What windows are you seeing the problem on?

Windows 11 Dev

### What FluentHub version/architecture are you seeing the problem on?

_None_

### Description

As the title

### Steps To Reproduce

1. Open app with no internel connection

### Expected behavior

_No response_

### Relevant Assets

_No response_

### PR DESCRIPTION
**Pull request by onein528**
**Resolved / Related Issues**

- Closes #27 
- Closes #43 
- Closes #10 

**Details of Changes**
Add details of changes here.
- Update Octokit classes security
- Add some pages
- Add some user controls
- Repository code page works property.

**Validation**
How did you test these changes?
- [x] Built and ran the app
- [ ] Tested the changes for accessibility

**Screenshots (optional)**

image

### CODE REVIEW

**Comment by onein528** [comment]
This updates will be big breaking changes inside code.

**Comment by BobbyESP** [comment]
Ok, nice!

**Comment by onein528** [comment]
do you have any idea with #43 ?
Currently, I have no ideas.

**Comment by BobbyESP** [comment]
> do you have any idea with #43 ? Currently, I have no ideas.

Later i see, these days i cant code :(

**Comment by BobbyESP** [comment]
But try to find the bug with line breakers

**Comment by onein528** [comment]
no, it seems that you have focus to your exams.

no problem!!

**Comment by BobbyESP** [comment]
This friday i'll be able to code! So i can take a look to it!

**Comment by BobbyESP** [comment]
Wow men, nice!!

**Comment by onein528** [comment]
I am replacing WebView block to WebView2 user control block.

BUT, I cannot load css file. it seems that schema is wrong. 0;0

image

**Comment by BobbyESP** [comment]
I'll take a look to it today to see if i can fix that and the buttons of the pinned repos

**Comment by BobbyESP** [comment]
Ok, so go with it! And yes, obviously that i can!

**Comment by BobbyESP** [comment]
I'll be a more active, hard exams finished (i have one next week but i think i can code a little)!

**Comment by onein528** [comment]
thats nice!!

**Comment by BobbyESP** [comment]
Nice!!

**Comment by BobbyESP** [comment]
Ok, maybe #43

**Comment by BobbyESP** [comment]
And after that, start doing settings page

**Comment by onein528** [comment]
LGTM!

**Comment by onein528** [comment]
i want the feature to be able to choose code syntax high lighting.

for example in C#

"using" directive: #FFFFFF

default C# keywords: #030303

this color change will commit to css file or like database file or app settings container or something.

**Comment by BobbyESP** [comment]
You mean in the text comparer?

**Comment by onein528** [comment]
yep. and also nop.

it is in markdown.

**Comment by BobbyESP** [comment]
> Reference in n

Oh, okk, nice!

**Comment by onein528** [comment]
image

Use x:Load directive by ViewModel binding to display or not.

**Comment by BobbyESP** [comment]
> Use x:Load directive by ViewModel binding to display or not.

Nice!! Sorry for not coding a lot :(

**Comment by onein528** [comment]
I have coded repo pages(especially code views), and you (will) code settings or something.
So. there is no need to worry about push conflict. and you dont need to be fast coding :)

**Comment by BobbyESP** [comment]
Ok, thanks men!!

**Comment by BobbyESP** [comment]
Omg men, the work that you are doing it's just incredible

**Comment by BobbyESP** [comment]
We are going to the heigh of Files hahaha

**Comment by onein528** [comment]
yeah. maybe haha

**Comment by BobbyESP** [comment]
Can you later see Discord?

**Comment by onein528** [comment]
Can you confirm that the list view of the repository is working properly?

I've just made it possible to refer to the codes.

**Comment by BobbyESP** [comment]
Yeah, give me a minutes and i try

**Comment by BobbyESP** [comment]
> Can you confirm that the list view of the repository is working properly?
> 
> I've just made it possible to refer to the codes(Enabled dir/file double tap).

Yep, it works properly!

**Comment by BobbyESP** [comment]
But well, theming made. Wow, it took me 2 hours

**Comment by BobbyESP** [comment]
image
Little things need to ba changed

**Comment by BobbyESP** [comment]
https://user-images.githubusercontent.com/60316747/153732786-a35064f9-38a2-4787-a2b7-56dde31afccb.mp4

**Comment by onein528** [comment]
nice!

**Comment by onein528** [comment]
> All works properly, excepts READMEs

fixed

**Comment by onein528** [comment]
image

**Comment by onein528** [comment]
Content that uses WebView, such as the README block, does not change the theme style when the app theme changes.

**Comment by onein528** [comment]
when you pushed your changes, marge this.

**Comment by BobbyESP** [comment]
> can you push?

Sorry i was sleeping :(

**Comment by BobbyESP** [comment]
> > All works properly, excepts READMEs
> 
> fixed

Nice!!

**Comment by BobbyESP** [comment]
> image
> 

Ohh yess

**Comment by onein528** [comment]
Yea. no problem!! let's marge!

**Comment by BobbyESP** [comment]
> when you pushed your changes, marge this.

Ok! But it has some visual bugs

**Comment by onein528** [comment]
ok. I will fix.

**Comment by BobbyESP** [comment]
> Yea. no problem!! let's marge and confirm changes!
> 
> can you marge for changes?

Ok! I go to the PC now. I',ve just woken up hahah

**Comment by onein528** [comment]
current main branch cannot build. so we need to marge this branch as so as we can

**Comment by BobbyESP** [comment]
Oh, i think we have conflicts

**Comment by BobbyESP** [comment]
Let me see

**Comment by BobbyESP** [comment]
Oh god. I think i made something bad, so i'm goingo to do a separated branch, and if it works properly, we merge that one with this

**Comment by onein528** [comment]
OK we marge right now?

**Comment by BobbyESP** [comment]
Ok, i think all it's fine

**Comment by onein528** [comment]
ok, I request you review

**Review by BobbyESP — APPROVED** [review]
Wow, really nice changes! Looks good to me!

**Comment by onein528** [comment]
LGTM

**Pull request merged**
