### PR TITLE
Update repository issue/PR pages

### PR DESCRIPTION
**Pull request by onein528**
**Resolved / Related Issues**
Items resolved / related issues by this PR.
- Closes #issue...
- Related #issue...

**Details of Changes**
Add details of changes here.
- Added...
- Fixed...

**Validation**
How did you test these changes?
- [ ] Built and ran the app
- [ ] Tested the changes for accessibility

**Screenshots (optional)**
Add screenshots here.

### CODE REVIEW

**Review by BobbyESP — DISMISSED** [review]
LGTM

**Comment by onein528** [comment]
Mock-up:

image

**Comment by onein528** [comment]
The color is not beautiful. we need  create one.

**Comment by onein528** [comment]
but we can only Critical and Success brush. ravender and gray brush is missing. we need to find.

**Comment by onein528** [comment]
Colored:

image

**Comment by BobbyESP** [comment]
> Mock-up:
> 
> image

Where you say empty, we can put the most recent action, or just this ->
image

**Comment by BobbyESP** [comment]
> but we can only Critical and Success brush. ravender and gray brush is missing. we need to find good colors.

Ok! No problem!

**Comment by onein528** [comment]
> > Mock-up:
> 
> > 
> 
> > image
> 
> 
> 
> Where you say empty, we can put the most recent action, or just this ->
> 
> image
> 
> 

yes it's possible

**Comment by BobbyESP** [comment]
Ok! Sorry men, these days i'm very stressed with the school

**Comment by onein528** [comment]
no. no problem.

**Comment by BobbyESP** [comment]
Yeah! By the moment all good, thanks! But you know, i have a lot of tasks to do (away form the exams) and wow, i'm not able to do nothing...

**Comment by onein528** [comment]
I understand. Don't be impatient, I think I can do my best for this project by myself.

**Comment by BobbyESP** [comment]
Ok! By the way i'm gonna try to do something!

**Comment by onein528** [comment]
We can now see the Issue's comments.

**Comment by onein528** [comment]
image

State colors became very good.

**Comment by BobbyESP** [comment]
Nice!!! Later i see all the changes! Now i'm studying for tomorrows exam :(

**Comment by BobbyESP** [comment]
But they all see very good!

**Comment by onein528** [comment]
image

**Comment by onein528** [comment]
this pr will marged. can you approve these changes?

**Comment by BobbyESP** [comment]
Wow!! That look incredible!!

**Comment by onein528** [comment]
image

**Comment by BobbyESP** [comment]
WOW!! Nice work men!! The app is going so good!

**Pull request merged**
