### PR TITLE
Update repository pages 2

### LINKED ISSUE #26: Create link like button style and label control
**Is your feature request related to a problem? Please describe.**

*None*

**Describe the solution you'd like**

Replace the link in the GitHub site with a button to update the style.
Create resource dictionary for this.

**Describe alternatives you've considered**

**Additional context**

**Screenshots (optional)**

Suggested place:

image

### LINKED ISSUE #31: Repository page ScrollViewer position
**Describe the bug**
As the title

**To Reproduce**
1. Go to repository page
2. Scroll down

**Expected behavior**

I don't know where to make it scrollable.

**Screenshots (optional)**

**Version**
 - Windows: Win11 22523.rs_prerelease
 - FluentHub: unversioning

**Additional context**

### PR DESCRIPTION
**Pull request by onein528**
**Resolved / Related Issues**

- Related #30
- Closes #31
- Closes #26

**Details of Changes**

*cannot describe about those changes. there are so many changes.*

**Validation**
How did you test these changes?
- [x] Built and ran the app
- [ ] Tested the changes for accessibility

**Screenshots (optional)**

### CODE REVIEW

**Comment by onein528** [comment]
I added XAML Formatter. So some xaml code quality will be improved.
Maybe you should add this extension too. This is the best.

**Comment by BobbyESP** [comment]
Ok, no problem! send me the link if you can!

**Comment by onein528** [comment]
Here! https://marketplace.visualstudio.com/items?itemName=TeamXavalon.XAMLStyler

**Comment by BobbyESP** [comment]
Ok, thanks!

**Comment by onein528** [comment]
Opps sorry this for vs2022
https://marketplace.visualstudio.com/items?itemName=TeamXavalon.XAMLStyler2022

**Comment by onein528** [comment]
nice !

**Comment by onein528** [comment]
Next we get all the events in an issue like this:

image

**Comment by onein528** [comment]
image

**Comment by onein528** [comment]
How do you feel?

image

**Comment by BobbyESP** [comment]
Nice!

**Comment by BobbyESP** [comment]
I can work on it now. Maybe not a lot of time, but i am able to work a little

**Comment by onein528** [comment]
You can develop organization page with your learning Octokit.net
I think causes a merge collision.

**Comment by BobbyESP** [comment]
Yeah, i think so. I'm going with it.

**Comment by BobbyESP** [comment]
But omg, octokit.net docs are... you know

**Comment by onein528** [comment]
hahaa. yeah I know. please wait a moment...

**Comment by BobbyESP** [comment]
No problem!

**Comment by onein528** [comment]
ok Then, can you improve the code base other than the repository page?

I cannot rightnow tell you how to use oktokit.

**Comment by BobbyESP** [comment]
Yeah, no problem!

**Comment by onein528** [comment]
Nice! thank you!!

**Comment by BobbyESP** [comment]
:)

**Comment by BobbyESP** [comment]
We can take a look to azure pipelines. It makes code revision

**Comment by onein528** [comment]
yeah. And we also add dependabot alert and dependent bot for detecting NuGet version updating. they create a pr for bumping them.

**Comment by BobbyESP** [comment]
Nice!

**Comment by BobbyESP** [comment]
Code factor is just importing i think so, so if you want, you can import it

**Comment by onein528** [comment]
But I dont know how to use. so study it:)

**Comment by BobbyESP** [comment]
Ok! I'll import it to my Nukite browser repo!

**Comment by BobbyESP** [comment]
image
Lmao hahaha

**Review by BobbyESP — APPROVED** [review]
They are all good!

**Review by BobbyESP — APPROVED** [review]

**Review by BobbyESP — DISMISSED** [review]

**Comment by onein528** [comment]
Images:

1. ScrollViewer position and rename user control "CodeFlyout" to "GitCloneFlyout" and updated it
    image

2. Issue list page
    image

3. PR list page
    image

4. Issue/PR page(currently same page)
    image

**Comment by onein528** [comment]
We can marge this. but pipeline deny.

```
##[error]No hosted parallelism has been purchased or granted. To request a free parallelism grant, please fill out the following form https://aka.ms/azpipelines-parallelism-request
```

This error happen.
The reason for this error is that a request was required to use the pipeline for free.
So we have to wait few days.

**Review by BobbyESP — APPROVED** [review]
All good! Omg bro, you're god in this.

**Comment by onein528** [comment]
THX :)

**Comment by BobbyESP** [comment]
> We can marge this. but pipeline deny.
> 
> ```
> ##[error]No hosted parallelism has been purchased or granted. To request a free parallelism grant, please fill out the following form https://aka.ms/azpipelines-parallelism-request
> ```
> 
> This error happen. The reason for this error is that a request was required to use the pipeline for free. So we have to wait few days.

Yeah, that's the problem. You can pass the pipeline hosting that with your own computer, but dont worry about that.

**Comment by BobbyESP** [comment]
> THX :)

:)) Sorry, i'm still learning how to use octokit, but now i think i know how it works without the docs kekw

**Comment by onein528** [comment]
OK. Actually, until I start developing this, I made about 6 repositories for studying Octokit.NET. It's that difficult, and others think it's the same.

Therefore, another goal of this project is to create a full documentation of Octokit.NET. I haven't decided on the specifics, but I hope it will come true.

**Comment by BobbyESP** [comment]
> OK. Actually, until I start developing this, I made about 6 repositories for studying Octokit.NET. It's that difficult, and others think it's the same.
> 
> Therefore, another goal of this project is to create a full documentation of Octokit.NET. I haven't decided on the specifics, but I hope it will come true.

Nicee bro!!

**Comment by onein528** [comment]
And I will create a markdown document for you in a private repository. The first is organization APIs.

**Comment by BobbyESP** [comment]
> And I will create a markdown document for you in a private repository. The first is organization APIs.

Ok, thanks!

**Comment by BobbyESP** [comment]
Everyone wishes they had someone like you working with them hahaha

**Comment by onein528** [comment]
You can see https://github.com/fluenthub-uwp/octokit.net-docs?

**Comment by BobbyESP** [comment]
> You can see https://github.com/fluenthub-uwp/octokit.net-docs?

Sure!

**Comment by onein528** [comment]
Nice!!

**Pull request merged**
