### PR TITLE
Create Pull Requests repo view

### PR DESCRIPTION
**Pull request by BobbyESP**
**Resolved / Related Issues**
Items resolved / related issues by this PR.

No one

**Details of Changes**
Add details of changes here.
- Adding pull requests view to the repositories

**Validation**
How did you test these changes?
- [ ] Built and ran the app
- [ ] Tested the changes for accessibility

**Screenshots (optional)**
Add screenshots here.

### CODE REVIEW

**Comment by onein528** [comment]
pls set title

And what purpose of this PR?

**Comment by onein528** [comment]
#35 is extremely complicated and this PR can cause complex conflicts.

**Comment by BobbyESP** [comment]
> #35 is extremely complicated and this PR can cause complex conflicts.

I know, i just leave this here because now i was testing octokit sorry :( Not necessary to touch this by the moment. We first need to do the issues one.

**Comment by onein528** [comment]
OK. understood.

**Comment by onein528** [comment]
And now that I have created the `approved` label, please set this label once you approve the PR.
Like this:
image

**Comment by BobbyESP** [comment]
Ok! Understood too! But i'm gonna close this one. You already made the PRs list! Nice work!

**Comment by onein528** [comment]
OKk.

**Pull request closed without merging**
